server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

  application:
    name: planup

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms

  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}  # Gmail 주소
    password: ${MAIL_PASSWORD}   # 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 86400000
  refreshTokenExpiration: 604800000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  packages-to-scan: com.planup.planup

logging:
  level:
    root: INFO
    com.planup.planup: DEBUG
    org.springframework.context.support: OFF
    org.springframework.boot.web: OFF
    reactor.core: OFF
    io.netty: OFF
    org.apache.catalina: OFF
    com.zaxxer.hikari: OFF
    org.hibernate: OFF

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: umc-planup-2025
    region: ap-northeast-2
kakao:
  client-id: ${REST_API_KEY}
  auth-url: https://kauth.kakao.com/oauth/token
  api-url: https://kapi.kakao.com/v2/user/me
  redirect-uri: http://localhost:8080/test/kakao/callback